# Generated by Django 5.2.17 on 2026-08-20 08:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_department_deleted_at'),
        ('patients', '0002_allergy_chroniccondition_consent_emergencycontact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.SmallIntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('checked_in', 'Checked In'), ('in_consultation', 'In Consultation'), ('completed', 'Completed'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('booking_channel', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('walk_in', 'Walk-in')], max_length=20)),
                ('created_by', models.ForeignKey(blank=True, help_text='Null if the patient self-booked via mobile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='core.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push'), ('email', 'Email')], max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='appointments.appointment')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.SmallIntegerField(help_text='0=Monday .. 6=Sunday, ISO-style.')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration_minutes', models.SmallIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_schedules', to='core.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['doctor', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queue_number', models.IntegerField()),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('priority', 'Priority'), ('emergency', 'Emergency')], default='normal', max_length=20)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='appointments.appointment')),
            ],
            options={
                'ordering': ['-priority', 'queue_number'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'scheduled_at'], name='appointment_doctor__2f3cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['department', 'scheduled_at'], name='appointment_departm_ecef39_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['scheduled', 'checked_in', 'in_consultation', 'completed'])), fields=('doctor', 'scheduled_at'), name='unique_active_appointment_per_doctor_slot'),
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_week__gte', 0), ('day_of_week__lte', 6)), name='doctor_schedule_day_of_week_range'),
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.CheckConstraint(condition=models.Q(('slot_duration_minutes__gt', 0)), name='doctor_schedule_positive_slot_duration'),
        ),
    ]
