# Generated by Django 5.2.17 on 2026-08-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="queueentry",
            options={
                "ordering": [
                    models.Case(
                        models.When(priority="emergency", then=0),
                        models.When(priority="priority", then=1),
                        default=2,
                        output_field=models.IntegerField(),
                    ),
                    "queue_number",
                ]
            },
        ),
    ]
