# Generated by Django 5.2.17 on 2026-08-20 07:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_department_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('record_id', models.UUIDField()),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('soft_delete', 'Soft delete')], max_length=20)),
                ('field_diff', models.JSONField(blank=True, help_text='Before/after values per field.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null for system-actor writes (e.g. a Celery job).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log_entries', to='core.facility')),
            ],
            options={
                'verbose_name_plural': 'audit log entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['facility', 'model_name', 'record_id'], name='audit_audit_facilit_2d5e51_idx'), models.Index(fields=['created_at'], name='audit_audit_created_3e5798_idx')],
            },
        ),
    ]
