# Generated by Django 5.2.17 on 2026-08-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_breakglassgrant'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='breakglassgrant',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='break_glass_reason_required'),
        ),
    ]
